### ISSUE TITLE
To run the trajectory yield the error

### ISSUE THREAD

**Issue by yang-guoli** [jiehanchong/membrane-depth-analysis#1]
I use the gmx trjconv to fit the trajectory to the protein, and run the command "python trajectory" yield the error as follow:
ValueError: Found array with 0 sample(s) (shape=(0, 3)) while a minimum of 1 is required

and i don't know how to solve it, could you help me ?

**Comment by jiehanchong** [comment]
Sorry for the delay - this is my first interaction with GitHub that isn't simply uploading or downloading a repository, and I don't seem to have the right notifications set up yet.
Before running the script, you have to run `gmx trjconv` on your trajectory, with the flag `-sep`, and with `.gro` as the file extension given to the `-o` option. This will convert your trajectory to a series of separate GRO files, which is what `depth_script.py` expects to see when run. The script only considers PO4 beads, so you can use an index to export only those beads in order to save drive space.
Make sure that the output goes to a folder that contains no other GRO files, as the script assumes all files in the folder are part of the trajectory.
You then navigate to the folder and run `depth_script.py` to perform the analysis.

**Comment by jiehanchong** [comment]
Is the code working for you now?

**Comment by yang-guoli** [comment]
>Yes，the code run very well and thanks for your help.
